//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoggyServer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoggyServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] libopenjpeg_dotnet_2_1_3_0_dotnet_1_i686 {
            get {
                object obj = ResourceManager.GetObject("libopenjpeg_dotnet_2_1_3_0_dotnet_1_i686", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] libopenjpeg_dotnet_2_1_3_0_dotnet_1_x86_64 {
            get {
                object obj = ResourceManager.GetObject("libopenjpeg_dotnet_2_1_3_0_dotnet_1_x86_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;configuration&gt;
        ///    &lt;dllmap os=&quot;osx&quot; dll=&quot;openjpeg-dotnet.dll&quot; target=&quot;libopenjpeg-dotnet-2.1.3.0-dotnet-1.dylib&quot; /&gt;
        ///    &lt;dllmap os=&quot;!windows,osx&quot; cpu=&quot;x86-64,ia64&quot; dll=&quot;openjpeg-dotnet.dll&quot; target=&quot;libopenjpeg-dotnet-2.1.3.0-dotnet-1-x86_64&quot; /&gt;
        ///    &lt;dllmap os=&quot;!windows,osx&quot; cpu=&quot;x86-64,ia64&quot; dll=&quot;openjpeg-dotnet-x86_64.dll&quot; target=&quot;libopenjpeg-dotnet-2.1.3.0-dotnet-1-x86_64&quot; /&gt;
        ///    &lt;dllmap os=&quot;!windows,osx&quot; cpu=&quot;x86&quot; dll=&quot;openjpeg-dotnet.dll&quot; target=&quot;libopenjpeg-dotnet-2.1.3.0-dotnet-1-i686&quot; /&gt;
        ///    &lt;d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string OpenMetaverse_dll {
            get {
                return ResourceManager.GetString("OpenMetaverse_dll", resourceCulture);
            }
        }
    }
}
